AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM Template for the City Tasks Events project.'

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: provided.al2
    Architectures:
      - arm64

Resources:
  CityTasksEventsFunction:
    Type: 'AWS::Serverless::Function'
    Connectors:
      EventsTableConnector:
        Properties:
          Destination:
            Type: 'AWS::DynamoDB::Table'
            Arn: !GetAtt CityTasksEventsTable.Arn
          Permissions:
            - Write
    Properties:
      FunctionName: city-tasks-events-function
      CodeUri: src/city-tasks-events
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Events:
        TaskExecutionEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - com.hiperium.city.tasks
              detail-type:
                - TaskExecution
      Policies:
        - CloudWatchFullAccess
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          CITY_TASKS_TIME_ZONE: "-05:00"
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          AWS_ENDPOINT_OVERRIDE: ""
    Metadata:
      BuildMethod: makefile

  CityTasksEventsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Events
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: deviceId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: deviceId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CityTasksEventsFunction}"
      RetentionInDays: 7

Outputs:
  CityTasksEventsFunction:
    Description: "CityTasksEvents Lambda Function ARN."
    Value: !GetAtt CityTasksEventsFunction.Arn
  CityTasksEventsFunctionIamRole:
    Description: "Implicit IAM Role created for the CityTasksEvents function."
    Value: !GetAtt CityTasksEventsFunctionRole.Arn
