#####################################################################################
########################## Stage 1: Docker Builder Image ############################
####### https://github.com/graalvm/container/pkgs/container/graalvm-community #######
#####################################################################################
FROM ghcr.io/graalvm/graalvm-community:17.0.8-ol9 AS builder
WORKDIR /workspace/app
COPY mvnw                              mvnw
COPY .mvn                              .mvn
COPY pom.xml                           pom.xml
COPY src/city-tasks-api/pom.xml        src/city-tasks-api/pom.xml
RUN ./mvnw dependency:go-offline -B -f src/city-tasks-api/pom.xml
COPY src/city-tasks-api/src            src/city-tasks-api/src

RUN gu install native-image && \
    ./mvnw -T 4C clean native:compile -Pnative -DskipTests -f src/city-tasks-api/pom.xml -Ddependency-check.skip=true

#####################################################################################
#################### Stage 2: Docker Native Application Image #######################
###### https://github.com/oracle/container-images/pkgs/container/oraclelinux ########
#####################################################################################
FROM oraclelinux:9-slim
COPY --from=builder /workspace/app/src/city-tasks-api/target/city-tasks-api application

EXPOSE 8080
CMD ["sh", "-c", "./application"]
